### ISSUE TITLE
Crash when ticking bullet entity - stack overflow

### ISSUE THREAD

**Issue by Colin-J-Wood** [Lykrast/GunsWithoutRoses#12]
randomly, whilst attacking an entity with iron bullets, it is possible for the game to crash because the projectile returns "null" for its vehicle.

be weary...this stack overflow report is 2MB in size, spamming methods executing within methods.

[crash-2022-02-22_22.37.14-server.txt](https://github.com/Lykrast/GunsWithoutRoses/files/8120609/crash-2022-02-22_22.37.14-server.txt)

**Comment by Lykrast** [comment]
So the weird thing is that none of the Bullet code do anything with vehicles or passengers. In fact, it should behave the same with them as blaze fireballs (same parent class, and both of them do not reference/modify anything related to vehicle or passenger in their code). Also the `getVehicle` function got a Nullable annotation put on it so that means that's not where the problem is.

That stacktrace shows a LOT of mods messing around with whatever event caused the stack overflow, and I don't think I can really decipher it.

I suggest you try spamming some fire charges through a dispenser or something to see if it can get the same crash with all those mods. Would be worth a try since I don't see what they don't like about the bullets.

**Comment by Colin-J-Wood** [comment]
Having trouble playing the "lottery" to reproduce the issue.  Note that it only occurs when it kills an entity for some reason.

any idea what LivingEntity.sendImmune does.

**Comment by Colin-J-Wood** [comment]
Okay from what I understand, LivingEntity.sendImmune is a packet that tells the client the projectile flying on the server is immune.  It sounds like this is going wrong, as the mod is becoming recursive in these checks during bullet flight.

**Comment by Colin-J-Wood** [comment]
from what me and other devs can tell, your repository contains no code that breaks like this.  I will close this issue assuming it is another mod of some kind at fault.

**Comment by Lykrast** [comment]
Alright, hope you find what's causing it!

**Comment by Spudstak** [comment]
I'm also having this issue did you ever figure out what was causing it @Colin-J-Wood ?

**Comment by Kaleidio** [comment]
> Alright, hope you find what's causing it!

A mod called Fancy Damage Indicators (the one that supports floating points, not the other that does integers only), was causing the crash, as its Immune to damage checker would crash if the damage type was from a projectile.
