### ISSUE TITLE
Bullets visually cull when out of entity simulation range

### ISSUE THREAD

**Issue by Colin-J-Wood** [Lykrast/GunsWithoutRoses#14]
Bullets die when outside entity simulation range, resulting in players being unable to kill entities from a very long distance in the case of an entity that is not unloaded yet (such as an illager or an equipment wearing zombie), as the bullet's flight gets interrupted.

Might I suggest adding code so the entity only dies if it is about to enter an unloaded chunk.

**Comment by Colin-J-Wood** [comment]
I found in your code that you have an explicit lifetime check to kill the entity, so nothing in your code is unexpected.  it must be that the bullet itself isn't dying per se, but simply reaches out of rendering range and minecraft's server kills it as is vanilla

I wonder if there is a way you can flag each projectile to not die by server culling means, to only die when your timer expires.

**Comment by Lykrast** [comment]
The kill timer was put as bullets could fly out of chunk load distance and get frozen there, then when reloaded would continue flying until out of render distance again. Since they aren't affected by gravity, they could be stuck there forever and I didn't want that to happen.

I don't know how if I can fix that issue you're describing, I'll check a bit but don't expect anything, which is very sad for snipers.

**Comment by Colin-J-Wood** [comment]
to clarify what I'm actually asking for is for the projectile to continue rendering even if outside server simulation range.  it's a client side tweak.  I don't mind if the bullets die by leaving the chunk distance, I just want them to continue rendering.

come to think of it it might be an issue related to async Entity Culling mod which has its own maximum draw distance.  I will verify tonight
